### ISSUE TITLE
beacon-kit installation fails with the latest version

### ISSUE THREAD

**Issue by suhas-chikkanna** [berachain/beacon-kit#2319]
Hi,

I am using the following  to Run a node: https://docs.berachain.com/nodes/quickstart. However it fails with the following error (as in the screenshot). This is happening with the latest commit to the main branch(as of 21/12/2024).

I am using the following configuration for the machine:

**OS:** Ubuntu 22.04/Ubuntu 24.10
**Go:** 1.23.4

Steps to reproduce (As mentioned in the quickstart doc above: https://docs.berachain.com/nodes/quickstart) :

1). git clone https://github.com/berachain/beacon-kit;
2). cd beacon-kit;
3). make build;

<img width="1728" alt="Screenshot 2024-12-21 at 9 25 41 PM" src="https://github.com/user-attachments/assets/c80666b0-4897-4b6b-810e-13c574073f58" />

**Comment by codingwithmanny** [comment]
Hi @suhas-chikkanna closing this because the docs have not been updated to reflect the latest changes of beaconkit.

We'll be revising this shortly, but the anything related to the docs, they apply specifically for `bArtio` and only work with the latest version of `v0.2.0`

See release comments in the "Breaking" section https://github.com/berachain/beacon-kit/releases/tag/v0.7.0
<img width="950" alt="Screenshot 2024-12-21 at 12 11 01 PM" src="https://github.com/user-attachments/assets/55883bf5-e5d5-4f32-9a50-87a2de5741ab" />

**Comment by suhas-chikkanna** [comment]
@codingwithmanny Really sorry., This is also happening with [v0.2.0-alpha.8](https://github.com/berachain/beacon-kit/releases/tag/v0.2.0-alpha.8) and [v0.2.0-alpha.1](https://github.com/berachain/beacon-kit/releases/tag/v0.2.0-alpha.1).

<img width="1728" alt="Screenshot 2024-12-22 at 10 10 15 AM" src="https://github.com/user-attachments/assets/b7ecbdce-5cd2-40c4-8177-7f5b321798ae" />


<img width="1326" alt="Screenshot 2024-12-22 at 10 04 31 AM" src="https://github.com/user-attachments/assets/10968300-452b-4c6d-88bd-48d45138bbbd" />
